/**
 * GLOW UP AI — Catalogue produits (démarrage réel)
 * --------------------------------------------------
 * Chaque produit ci-dessous est un vrai produit du marché français
 * (pharmacie / parapharmacie), avec des informations vérifiées via
 * les fiches marque / distributeur (prix indicatifs, à réactualiser
 * régulièrement — ils bougent souvent selon les promos).
 *
 * ⚠️ Toujours revérifier les mentions légales / allergènes / grossesse
 * directement sur l'emballage avant affichage final — les formules
 * changent parfois sans préavis.
 *
 * Respecte le schéma Product défini dans matching-engine.js
 *
 * PHOTOS PRODUIT : ajoute un champ `image: "/products/<id>.jpg"` sur un
 * produit une fois que tu as une vraie photo (achetée/licenciée, fournie par
 * la marque, ou prise par toi) placée dans `public/products/<id>.jpg` du
 * projet Vite. Sans ce champ, l'app affiche automatiquement une icône de
 * remplacement selon le format (sérum/crème/gel/lotion) — aucun lien externe
 * n'est utilisé, pour éviter les images cassées ou les soucis de droits.
 *
 * CODE-BARRES (`ean`) — pour le mode "scanner en rayon" (façon Yuka).
 * 4 produits sur 29 ont un vrai code confirmé par recoupement d'au moins
 * 2 sources indépendantes (lrp_effaclarduo, cerave_hydratante,
 * the_ordinary_niacinamide, beautyofjoseon_glow_serum). Les 25 autres ont
 * volontairement `ean` absent plutôt qu'un faux code inventé qui casserait
 * le scanner. À compléter : 1) vérifier Open Beauty Facts
 * (https://world.openbeautyfacts.org/api/v2/product/<code>.json, licence
 * ouverte ODbL), 2) sinon relever à la main sur l'emballage.
 */

export const REAL_PRODUCTS = [
  {
    id: "lrp_effaclarduo",
    name: "La Roche-Posay Effaclar Duo+M",
    brand: "La Roche-Posay",
    price: 13.9,
    volume: "40 ml",
    skinTypes: ["grasse", "mixte"],
    concerns: ["acne", "points_noirs", "taches"],
    pores: ["dilates"],
    categories: ["traitement"],
    styles: ["classique", "toutes"],
    ageRange: [15, 55],
    lifestyle: ["non_comedogene", "hypoallergenique"],
    keyIngredients: ["Niacinamide (~2-3%)", "LHA", "Phylobioma"],
    format: "creme",
    zones: ["visage", "zone_t"],
    ean: "3337875863377",
    note: "Anti-imperfections, réduit points noirs et marques post-acné. Éviter le contour des yeux.",
  },
  {
    id: "cerave_hydratante",
    name: "CeraVe Crème Hydratante Visage",
    brand: "CeraVe",
    price: 12.5,
    volume: "52 ml",
    skinTypes: ["seche", "mixte", "toutes"],
    concerns: ["rougeurs"],
    pores: ["normaux", "toutes"],
    categories: ["hydratation"],
    styles: ["classique", "toutes"],
    ageRange: [12, 90],
    lifestyle: ["sans_parfum", "non_comedogene"],
    keyIngredients: ["Céramides NP/AP/EOP", "Niacinamide", "Acide hyaluronique"],
    format: "creme",
    zones: ["visage"],
    ean: "3337875597449",
    note: "Technologie MVE : libération progressive des actifs sur 24h. Convient aussi aux peaux desséchées par un traitement anti-acné.",
  },
  {
    id: "avene_antirougeurs",
    name: "Avène Antirougeurs CLEAN",
    brand: "Avène",
    price: 14.0,
    volume: "400 ml",
    skinTypes: ["toutes"],
    concerns: ["rougeurs"],
    pores: ["toutes"],
    categories: ["nettoyage"],
    styles: ["classique", "toutes"],
    ageRange: [12, 90],
    lifestyle: ["sans_parfum", "sans_savon"],
    keyIngredients: ["Eau thermale d'Avène", "TRP-Regulin™"],
    format: "lotion",
    zones: ["visage"],
    priceConfirmed: false,
    note: "⚠️ À VÉRIFIER : le site officiel Avène (US) indique que la gamme Antirougeurs CLEAN a été discontinuée, remplacée par 'Redness Expert'. Lait nettoyant sans rinçage, formulé pour les peaux sujettes aux rougeurs et sensibles — à confirmer que ce produit est toujours vendu en France avant tout affichage public ou lien d'achat.",
  },
  {
    id: "loreal_ageperfect_serum",
    name: "L'Oréal Paris Age Perfect Le Duo Sérum",
    brand: "L'Oréal Paris",
    price: 22.0,
    volume: "30 ml",
    skinTypes: ["toutes"],
    concerns: ["rides", "taches"],
    pores: ["toutes"],
    categories: ["traitement"],
    styles: ["age_perfect"],
    ageRange: [35, 75],
    lifestyle: [],
    keyIngredients: ["Peptides de collagène", "Vitamine B3 (niacinamide)", "Vitamine Cg"],
    format: "serum",
    zones: ["visage"],
    note: "Double sérum raffermissant + éclat, pensé pour les peaux matures dès l'apparition des premiers signes de l'âge.",
  },
  {
    id: "loreal_ageperfect_creme",
    name: "L'Oréal Paris Age Perfect Collagen Expert Crème Jour SPF 30",
    brand: "L'Oréal Paris",
    price: 19.0,
    volume: "50 ml",
    skinTypes: ["toutes"],
    concerns: ["rides", "taches"],
    pores: ["toutes"],
    categories: ["hydratation"],
    styles: ["age_perfect"],
    ageRange: [35, 75],
    lifestyle: [],
    keyIngredients: ["Collagène", "Peptides de soja", "Melanin-Block", "SPF 30"],
    format: "creme",
    zones: ["visage"],
    note: "Crème de jour raffermissante avec protection solaire intégrée, cible aussi les taches pigmentaires.",
  },
  {
    id: "cosrx_snail96",
    name: "COSRX Advanced Snail 96 Mucin Power Essence",
    brand: "COSRX",
    price: 19.9,
    volume: "100 ml",
    skinTypes: ["toutes"],
    concerns: ["rougeurs", "exces_sebum"],
    pores: ["toutes"],
    categories: ["hydratation"],
    styles: ["coreenne"],
    ageRange: [15, 60],
    lifestyle: ["sans_parfum"],
    keyIngredients: ["Mucine d'escargot (96%)", "Acide hyaluronique sodique", "Panthénol"],
    format: "serum",
    zones: ["visage"],
    note: "Essence emblématique de la routine coréenne, renforce la barrière cutanée et apaise les peaux sensibles ou post-acnéiques.",
  },
  {
    id: "byoma_glow_serum",
    name: "Byoma Phyto-Mucin Glow Serum",
    brand: "Byoma",
    price: 16.5,
    priceConfirmed: true,
    volume: "40 ml",
    skinTypes: ["toutes"],
    concerns: ["rides"],
    pores: ["toutes"],
    categories: ["hydratation"],
    styles: ["coreenne", "toutes"],
    ageRange: [15, 60],
    lifestyle: ["vegan"],
    keyIngredients: ["Phyto-mucine (végane)", "Céramides", "Peptides"],
    format: "serum",
    zones: ["visage"],
    note: "Alternative végane à la mucine d'escargot, avec un profil ingrédients plus complet (céramides, peptides).",
  },
  {
    id: "typology_serum_l36",
    name: "Typology Sérum Unifiant L36",
    brand: "Typology",
    price: 17.9,
    priceConfirmed: false,
    volume: "10 ml",
    skinTypes: ["toutes"],
    concerns: ["rougeurs", "taches"],
    pores: ["toutes"],
    categories: ["traitement"],
    styles: ["classique", "toutes"],
    ageRange: [15, 60],
    lifestyle: [],
    keyIngredients: ["Niacinamide (12%)"],
    format: "serum",
    zones: ["visage"],
    note: "Cible les rougeurs liées aux imperfections (marques post-acné) — la marque déconseille ce sérum pour les rougeurs d'hypersensibilité/rosacée.",
  },
  {
    id: "aromazone_niacinamide",
    name: "Aroma-Zone Sérum Concentré Niacinamide 10%, Cuivre & Zinc",
    brand: "Aroma-Zone",
    price: 11.9,
    priceConfirmed: true,
    volume: "30 ml",
    skinTypes: ["grasse", "mixte"],
    concerns: ["points_noirs", "rougeurs", "taches", "exces_sebum"],
    pores: ["dilates"],
    categories: ["traitement"],
    styles: ["classique", "toutes"],
    ageRange: [15, 55],
    lifestyle: ["sans_parfum"],
    keyIngredients: ["Niacinamide (10%)", "Zinc PCA", "Cuivre PCA", "Acide hyaluronique"],
    format: "serum",
    zones: ["visage", "zone_t"],
    note: "Formule naturelle française, resserre les pores et régule le sébum. Bon rapport qualité-prix pour du 10% niacinamide.",
  },
  {
    id: "the_ordinary_niacinamide",
    name: "The Ordinary Niacinamide 10% + Zinc 1%",
    brand: "The Ordinary",
    price: 6.0,
    priceConfirmed: true,
    volume: "30 ml",
    skinTypes: ["grasse", "mixte"],
    concerns: ["points_noirs", "exces_sebum"],
    pores: ["dilates"],
    categories: ["traitement"],
    styles: ["classique", "toutes"],
    ageRange: [15, 55],
    lifestyle: [],
    keyIngredients: ["Niacinamide (10%)", "Zinc PCA"],
    format: "serum",
    zones: ["visage", "zone_t"],
    ean: "0769915190311",
    note: "Référence du marché pour son rapport prix/efficacité — bon produit d'entrée de gamme pour un MVP.",
  },
  {
    id: "bioderma_sensibio_ar",
    name: "Bioderma Sensibio AR+ Bi-Sérum",
    brand: "Bioderma",
    price: 24.7,
    priceConfirmed: true,
    volume: "30 ml",
    skinTypes: ["toutes"],
    concerns: ["rougeurs", "rides"],
    pores: ["toutes"],
    categories: ["traitement"],
    styles: ["classique", "toutes"],
    ageRange: [25, 65],
    lifestyle: ["sans_parfum"],
    keyIngredients: ["Bakuchiol", "Complexe anti-rougeurs Rosactiv"],
    format: "serum",
    zones: ["visage"],
    note: "Double action anti-rougeurs et anti-âge, pensé pour les peaux sensibles à tendance couperosique.",
  },
  {
    id: "eucerin_hyaluron_filler",
    name: "Eucerin Hyaluron-Filler Sérum",
    brand: "Eucerin",
    price: 25.0,
    priceConfirmed: false,
    volume: "30 ml",
    skinTypes: ["toutes"],
    concerns: ["rides"],
    pores: ["toutes"],
    categories: ["hydratation"],
    styles: ["age_perfect"],
    ageRange: [35, 75],
    lifestyle: [],
    keyIngredients: ["Acide hyaluronique pur"],
    format: "serum",
    zones: ["visage"],
    note: "Gamme anti-âge très établie en pharmacie ; prix à reconfirmer selon le format exact (sérum vs. booster vs. crème).",
  },
  {
    id: "centellian24_madeca_cream",
    name: "Centellian24 Madeca Cream",
    brand: "Centellian24",
    price: 22.0,
    priceConfirmed: false,
    volume: "50 ml",
    skinTypes: ["seche", "mixte", "toutes"],
    concerns: ["rougeurs"],
    pores: ["toutes"],
    categories: ["hydratation"],
    styles: ["coreenne"],
    ageRange: [15, 60],
    lifestyle: [],
    keyIngredients: ["Centella Asiatica", "Madecassoside", "Panthénol"],
    format: "creme",
    zones: ["visage"],
    note: "Crème apaisante barrière, référence coréenne du soin à la centella asiatica pour peaux sensibles/réactives.",
  },
  {
    id: "beautyofjoseon_glow_serum",
    name: "Beauty of Joseon Glow Serum Propolis + Niacinamide",
    brand: "Beauty of Joseon",
    price: 17.0,
    priceConfirmed: true,
    volume: "30 ml",
    skinTypes: ["toutes"],
    concerns: ["points_noirs", "exces_sebum", "rougeurs", "taches"],
    pores: ["dilates", "toutes"],
    categories: ["traitement"],
    styles: ["coreenne"],
    ageRange: [15, 55],
    lifestyle: [],
    keyIngredients: ["Propolis (60%)", "Niacinamide (2%)"],
    format: "serum",
    zones: ["visage", "zone_t"],
    ean: "8809657114960",
    note: "Best-seller K-beauty, texture miel, régule le sébum et resserre les pores tout en apaisant.",
  },
  {
    id: "erborian_ginseng_power",
    name: "Erborian Ginseng Power Crème",
    brand: "Erborian",
    price: 35.0,
    priceConfirmed: true,
    volume: "50 ml",
    skinTypes: ["toutes"],
    concerns: ["rides"],
    pores: ["toutes"],
    categories: ["hydratation"],
    styles: ["coreenne", "age_perfect"],
    ageRange: [30, 75],
    lifestyle: [],
    keyIngredients: ["Ginseng"],
    format: "creme",
    zones: ["visage"],
    note: "Marque hybride franco-coréenne, positionnement anti-âge premium — bon pont entre les styles coréen et age perfect.",
  },
  {
    id: "acm_rosakalm",
    name: "ACM Rosakalm Crème Anti-Rougeurs",
    brand: "Labo ACM",
    price: 16.0,
    priceConfirmed: false,
    volume: "40 ml",
    skinTypes: ["toutes"],
    concerns: ["rougeurs"],
    pores: ["toutes"],
    categories: ["hydratation"],
    styles: ["classique", "toutes"],
    ageRange: [18, 70],
    lifestyle: [],
    keyIngredients: [],
    format: "creme",
    zones: ["visage"],
    note: "Marque dermo-cosmétique française spécialisée rougeurs/couperose. Prix à reconfirmer directement chez le distributeur.",
  },
  {
    id: "lrp_cicaplast_mains",
    name: "La Roche-Posay Cicaplast Mains",
    brand: "La Roche-Posay",
    price: 6.49,
    priceConfirmed: true,
    volume: "50 ml",
    skinTypes: ["toutes"],
    concerns: ["rougeurs"],
    pores: ["toutes"],
    categories: ["traitement", "hydratation"],
    styles: ["classique", "toutes"],
    ageRange: [12, 90],
    lifestyle: ["sans_parfum"],
    format: "creme",
    zones: ["mains"],
    keyIngredients: ["Niacinamide (4%)", "Glycérine (30%)", "Beurre de karité"],
    note: "Crème barrière réparatrice pour mains sur-sollicitées, sèches ou abîmées (eczéma, froid, lavages fréquents). Réduit rougeurs et rugosités dès la 1ère application.",
  },
  {
    id: "guerlain_abeille_royale_mains",
    name: "Guerlain Abeille Royale Baume Réparateur Jeunesse Des Mains",
    brand: "Guerlain",
    price: 36.95,
    priceConfirmed: true,
    volume: "75 ml",
    skinTypes: ["toutes"],
    concerns: ["rides"],
    pores: ["toutes"],
    categories: ["traitement"],
    styles: ["age_perfect"],
    ageRange: [35, 75],
    lifestyle: [],
    format: "creme",
    zones: ["mains"],
    keyIngredients: ["Concentré de miels", "Gelée royale", "Beurre de karité"],
    note: "Positionnement anti-âge premium pour les mains : raffermit, lisse et repulpe la peau, fortifie les ongles. +103% d'hydratation mesurée après 6h.",
  },
  {
    id: "clarins_hand_nail",
    name: "Clarins Hand and Nail Treatment Cream",
    brand: "Clarins",
    price: 38.0,
    priceConfirmed: false,
    volume: "100 ml",
    skinTypes: ["toutes"],
    concerns: [],
    pores: ["toutes"],
    categories: ["hydratation"],
    styles: ["classique", "toutes"],
    ageRange: [18, 90],
    lifestyle: ["vegan"],
    format: "creme",
    zones: ["mains"],
    keyIngredients: ["Beurre de karité", "Huile de sésame", "Extrait de myrrhe"],
    note: "Best-seller Clarins, texture légère non grasse, protège du dessèchement et fortifie ongles/cuticules. Prix France à reconfirmer (donnée trouvée en $ US).",
  },
  {
    id: "avene_coldcream_mains",
    name: "Avène Cold Cream Crème Mains Concentrée",
    brand: "Avène",
    price: 7.0,
    priceConfirmed: false,
    volume: "50 ml",
    skinTypes: ["toutes"],
    concerns: [],
    pores: ["toutes"],
    categories: ["hydratation"],
    styles: ["classique", "toutes"],
    ageRange: [2, 90],
    lifestyle: ["sans_parfum"],
    format: "creme",
    zones: ["mains"],
    keyIngredients: ["Eau thermale d'Avène", "Sucralfate", "Beurre de karité"],
    note: "Pour mains très sèches, gercées ou abîmées par le froid/lavages fréquents. Convient dès 2 ans, toute la famille. Prix estimé, à reconfirmer.",
  },
  {
    id: "savonnerie_nyons_mains",
    name: "La Savonnerie de Nyons Crème Mains Aloe Vera Bio",
    brand: "La Savonnerie de Nyons",
    price: 12.9,
    priceConfirmed: false,
    volume: "75 ml",
    skinTypes: ["toutes"],
    concerns: [],
    pores: ["toutes"],
    categories: ["hydratation"],
    styles: ["classique", "toutes"],
    ageRange: [12, 90],
    lifestyle: ["bio"],
    format: "creme",
    zones: ["mains"],
    keyIngredients: ["Aloe vera bio", "Huile d'argan bio", "Beurre de karité"],
    note: "Petite savonnerie artisanale française (Nyons, Drôme). Prix aligné sur le format 75ml de la gamme (confirmé sur une variante voisine, à revérifier pour l'Aloe Vera).",
  },
  {
    id: "payot_micropeeling_pieds",
    name: "Payot Baume Fondant Micro-Peeling Pieds",
    brand: "Payot",
    price: 15.0,
    priceConfirmed: false,
    volume: "40 ml",
    skinTypes: ["toutes"],
    concerns: [],
    pores: ["toutes"],
    categories: ["traitement"],
    styles: ["classique", "toutes"],
    ageRange: [18, 90],
    lifestyle: [],
    format: "creme",
    zones: ["pieds"],
    keyIngredients: ["Urée (10%)", "Huile de graines d'écume des prés"],
    note: "Kératolytique pour talons secs, rugosités et callosités. L'urée à 10% est le dosage jugé idéal pour l'efficacité sans irriter. Prix estimé, à reconfirmer.",
  },
  {
    id: "cicamanuka_mains",
    name: "CicaManuka Soin Mains Réparateur Miel de Manuka IAA15+",
    brand: "CicaManuka",
    price: 8.9,
    priceConfirmed: true,
    volume: "50 ml",
    skinTypes: ["seche", "toutes"],
    concerns: [],
    pores: ["toutes"],
    categories: ["hydratation", "traitement"],
    styles: ["classique", "toutes"],
    ageRange: [15, 90],
    lifestyle: ["bio"],
    format: "creme",
    zones: ["mains"],
    keyIngredients: ["Miel de Manuka IAA15+ (5%)", "Beurre de karité bio", "Huile d'olive bio"],
    note: "Miel de Manuka néo-zélandais à indice IAA garanti (concentration en méthylglyoxal, action apaisante/réparatrice certifiée). Pour mains sèches, fragilisées, agressées par le quotidien. Marque française (Lille).",
  },
  {
    id: "cicamanuka_pieds",
    name: "CicaManuka Crème Pieds Réparatrice Miel de Manuka IAA15+",
    brand: "CicaManuka",
    price: 9.99,
    priceConfirmed: true,
    volume: "75 ml",
    skinTypes: ["seche", "toutes"],
    concerns: [],
    pores: ["toutes"],
    categories: ["hydratation", "traitement"],
    styles: ["classique", "toutes"],
    ageRange: [3, 90],
    lifestyle: ["bio"],
    format: "creme",
    zones: ["pieds"],
    keyIngredients: [
      "Miel de Manuka IAA15+",
      "Beurre de karité bio",
      "Aloe vera",
      "Acide citrique & gluconolactone (kératolytique)",
    ],
    note: "Réduit les callosités, apaise les talons abîmés/fendillés et aide à prévenir les crevasses. Convient dès 3 ans, aux femmes enceintes et allaitantes. Prix confirmé entre 9,99€ et 10,99€ selon le distributeur.",
  },
  {
    id: "typology_serum_yeux_l33",
    name: "Typology Sérum Cernes et Poches L33",
    brand: "Typology",
    price: 16.9,
    priceConfirmed: false,
    volume: "15 ml",
    skinTypes: ["toutes"],
    concerns: [],
    pores: ["toutes"],
    categories: ["traitement"],
    styles: ["classique", "toutes"],
    ageRange: [18, 70],
    lifestyle: [],
    format: "serum",
    zones: ["yeux"],
    keyIngredients: ["Caféine (5%)", "Niacinamide (5%)", "Extrait d'Albizia Julibrissin"],
    note: "Cible spécifiquement les cernes vasculaires (bleutés/violacés) et les poches — n'agit pas sur les cernes bruns pigmentaires ni les cernes creux. Non contre-indiqué grossesse/allaitement.",
  },
  {
    id: "caudalie_creme_yeux_premier_cru",
    name: "Caudalie La Crème Yeux Premier Cru",
    brand: "Caudalie",
    price: 42.0,
    priceConfirmed: false,
    volume: "15 ml",
    skinTypes: ["toutes"],
    concerns: ["rides"],
    pores: ["toutes"],
    categories: ["traitement"],
    styles: ["age_perfect", "toutes"],
    ageRange: [35, 75],
    lifestyle: [],
    format: "creme",
    zones: ["yeux"],
    keyIngredients: ["Acide hyaluronique", "Brevet Longévité (Caudalie x Harvard Medical School)", "Nacres 100% naturelles"],
    note: "Embout métallique massant décongestionnant. Corrige rides du contour des yeux et des lèvres, réduit cernes et poches.",
  },
  {
    id: "cosrx_snail_peptide_eye",
    name: "COSRX Advanced Snail Peptide Eye Cream",
    brand: "COSRX",
    price: 17.0,
    priceConfirmed: false,
    volume: "25 ml",
    skinTypes: ["toutes"],
    concerns: ["rides"],
    pores: ["toutes"],
    categories: ["traitement", "hydratation"],
    styles: ["coreenne"],
    ageRange: [18, 65],
    lifestyle: [],
    format: "creme",
    zones: ["yeux"],
    keyIngredients: ["Mucine d'escargot", "Complexe 5 peptides", "Niacinamide", "Acide hyaluronique"],
    note: "Extension de l'essence Snail 96. Formule légère, non testée sur animaux, contenant utilisée hors du contact direct avec l'œil.",
  },
  {
    id: "beautyofjoseon_revive_eye",
    name: "Beauty of Joseon Revive Eye Serum : Ginseng + Retinal",
    brand: "Beauty of Joseon",
    price: 19.0,
    priceConfirmed: false,
    volume: "30 ml",
    skinTypes: ["toutes"],
    concerns: ["rides"],
    pores: ["toutes"],
    categories: ["traitement"],
    styles: ["coreenne", "age_perfect"],
    ageRange: [25, 65],
    lifestyle: [],
    format: "serum",
    zones: ["yeux"],
    keyIngredients: ["Ginseng", "Rétinal", "Galactomyces Ferment Filtrate"],
    note: "⚠️ Contient du rétinal (rétinoïde) — à introduire progressivement, à éviter en cas de grossesse/allaitement (à vérifier sur l'emballage) et à ne jamais combiner avec un autre rétinoïde.",
  },
  {
    id: "clarins_concentre_cou_decollete",
    name: "Clarins Concentré Décolleté et Cou Anti-Tache Multi-Intensive",
    brand: "Clarins",
    price: 94.0,
    priceConfirmed: true,
    volume: "75 ml",
    skinTypes: ["toutes"],
    concerns: ["rides", "taches"],
    pores: ["toutes"],
    categories: ["traitement"],
    styles: ["age_perfect"],
    ageRange: [50, 85],
    lifestyle: [],
    format: "creme",
    zones: ["cou"],
    keyIngredients: ["Extraits végétaux redensifiants", "Complexe anti-taches"],
    note: "Ligne Multi-Intensive pensée pour les peaux matures (50 ans et +) : redensifie, lisse, atténue les taches du cou et du décolleté. Positionnement premium.",
  },
];

/**
 * Note sur les concerns des soins mains/pieds : la taxonomie actuelle
 * (acne, points_noirs, rougeurs, rides, taches, exces_sebum) a été pensée
 * pour le visage. La plupart des soins mains/pieds ci-dessus répondent à des
 * problématiques qui n'y figurent pas (sécheresse, callosités, gerçures) —
 * j'ai laissé `concerns: []` plutôt que de forcer un tag inexact. Résultat
 * concret : ces produits seront pénalisés sur le critère "concerns" (33% du
 * score) même quand ils sont parfaitement pertinents pour la zone demandée.
 * Pour un vrai lancement de la fonctionnalité mains/pieds, il faudrait
 * ajouter des concerns dédiés au corps (ex. "secheresse", "callosites",
 * "gercures") au moteur de matching plutôt que de réutiliser ceux du visage.
 */

/**
 * Marques demandées (mains/pieds) mais non intégrées faute de données
 * fiables trouvées : Yumi, Skybottle, Nijiko, Univeda, Alvadiem, Douce
 * Nature. Idem pour un produit mains/pieds précis chez Roger & Gallet ou
 * Aroma-Zone.
 *
 * Marques demandées pour "yeux" mais non intégrées faute de données
 * fiables trouvées : Dr Pierre Ricaud, Paula's Choice, Horace, Yves Rocher,
 * Aroma-Zone, Théobroma, Green Tangerine, Belif Aqua Bomb, Haruharu Wonder,
 * Medicube, Laneige, Innisfree Green, Hanskin Real Complexion, Abib, TirTir,
 * Nuxe, Erborian.
 *
 * Marques demandées pour "cou/décolleté" mais non intégrées faute de
 * données fiables trouvées : Cellexia, goPure, HSBCC, OLAY, ActivScience,
 * Dr Pierre Ricaud, Sisley, L'Oréal, Annemarie Börlind, Dr. Hauschka,
 * bareMinerals, La Mer, Lierac, Erborian, Nuxe, RoC, Dr. Barbara Sturm,
 * Patyka, CurrentBody, Yaman, COSRX, Medipeel, Dr.Melaxin, DERMATORY, CKD.
 *
 * CicaManuka a une gamme plus large que les 2 produits ici (mains + pieds) :
 * baume corps IAA10+, crème apaisante visage/corps IAA15+, crème réparatrice
 * IAA10+, soin lèvres, sérum régénérant visage. Pas encore intégrés — à
 * ajouter si tu veux enrichir encore le visage/corps avec cette marque.
 */
