/**
 * GLOW UP AI — Catalogue produits (démarrage réel)
 * --------------------------------------------------
 * Chaque produit ci-dessous est un vrai produit du marché français
 * (pharmacie / parapharmacie), avec des informations vérifiées via
 * les fiches marque / distributeur (prix indicatifs, à réactualiser
 * régulièrement — ils bougent souvent selon les promos).
 *
 * ⚠️ Toujours revérifier les mentions légales / allergènes / grossesse
 * directement sur l'emballage avant affichage final — les formules
 * changent parfois sans préavis.
 *
 * Respecte le schéma Product défini dans matching-engine.js
 */

export const REAL_PRODUCTS = [
  {
    id: "lrp_effaclarduo",
    name: "La Roche-Posay Effaclar Duo+M",
    brand: "La Roche-Posay",
    price: 13.9,
    volume: "40 ml",
    skinTypes: ["grasse", "mixte"],
    concerns: ["acne", "points_noirs", "taches"],
    pores: ["dilates"],
    categories: ["traitement"],
    styles: ["classique", "toutes"],
    ageRange: [15, 55],
    lifestyle: ["non_comedogene", "hypoallergenique"],
    keyIngredients: ["Niacinamide (~2-3%)", "LHA", "Phylobioma"],
    format: "creme",
    note: "Anti-imperfections, réduit points noirs et marques post-acné. Éviter le contour des yeux.",
  },
  {
    id: "cerave_hydratante",
    name: "CeraVe Crème Hydratante Visage",
    brand: "CeraVe",
    price: 12.5,
    volume: "52 ml",
    skinTypes: ["seche", "mixte", "toutes"],
    concerns: ["rougeurs"],
    pores: ["normaux", "toutes"],
    categories: ["hydratation"],
    styles: ["classique", "toutes"],
    ageRange: [12, 90],
    lifestyle: ["sans_parfum", "non_comedogene"],
    keyIngredients: ["Céramides NP/AP/EOP", "Niacinamide", "Acide hyaluronique"],
    format: "creme",
    note: "Technologie MVE : libération progressive des actifs sur 24h. Convient aussi aux peaux desséchées par un traitement anti-acné.",
  },
  {
    id: "avene_antirougeurs",
    name: "Avène Antirougeurs CLEAN",
    brand: "Avène",
    price: 14.0,
    volume: "400 ml",
    skinTypes: ["toutes"],
    concerns: ["rougeurs"],
    pores: ["toutes"],
    categories: ["nettoyage"],
    styles: ["classique", "toutes"],
    ageRange: [12, 90],
    lifestyle: ["sans_parfum", "sans_savon"],
    keyIngredients: ["Eau thermale d'Avène", "TRP-Regulin™"],
    format: "lotion",
    note: "Lait nettoyant sans rinçage, formulé pour les peaux sujettes aux rougeurs et sensibles.",
  },
  {
    id: "loreal_ageperfect_serum",
    name: "L'Oréal Paris Age Perfect Le Duo Sérum",
    brand: "L'Oréal Paris",
    price: 22.0,
    volume: "30 ml",
    skinTypes: ["toutes"],
    concerns: ["rides", "taches"],
    pores: ["toutes"],
    categories: ["traitement"],
    styles: ["age_perfect"],
    ageRange: [35, 75],
    lifestyle: [],
    keyIngredients: ["Peptides de collagène", "Vitamine B3 (niacinamide)", "Vitamine Cg"],
    format: "serum",
    note: "Double sérum raffermissant + éclat, pensé pour les peaux matures dès l'apparition des premiers signes de l'âge.",
  },
  {
    id: "loreal_ageperfect_creme",
    name: "L'Oréal Paris Age Perfect Collagen Expert Crème Jour SPF 30",
    brand: "L'Oréal Paris",
    price: 19.0,
    volume: "50 ml",
    skinTypes: ["toutes"],
    concerns: ["rides", "taches"],
    pores: ["toutes"],
    categories: ["hydratation"],
    styles: ["age_perfect"],
    ageRange: [35, 75],
    lifestyle: [],
    keyIngredients: ["Collagène", "Peptides de soja", "Melanin-Block", "SPF 30"],
    format: "creme",
    note: "Crème de jour raffermissante avec protection solaire intégrée, cible aussi les taches pigmentaires.",
  },
  {
    id: "cosrx_snail96",
    name: "COSRX Advanced Snail 96 Mucin Power Essence",
    brand: "COSRX",
    price: 19.9,
    volume: "100 ml",
    skinTypes: ["toutes"],
    concerns: ["rougeurs", "exces_sebum"],
    pores: ["toutes"],
    categories: ["hydratation"],
    styles: ["coreenne"],
    ageRange: [15, 60],
    lifestyle: ["sans_parfum"],
    keyIngredients: ["Mucine d'escargot (96%)", "Acide hyaluronique sodique", "Panthénol"],
    format: "serum",
    note: "Essence emblématique de la routine coréenne, renforce la barrière cutanée et apaise les peaux sensibles ou post-acnéiques.",
  },
  {
    id: "byoma_glow_serum",
    name: "Byoma Phyto-Mucin Glow Serum",
    brand: "Byoma",
    price: 16.5,
    priceConfirmed: true,
    volume: "40 ml",
    skinTypes: ["toutes"],
    concerns: ["rides"],
    pores: ["toutes"],
    categories: ["hydratation"],
    styles: ["coreenne", "toutes"],
    ageRange: [15, 60],
    lifestyle: ["vegan"],
    keyIngredients: ["Phyto-mucine (végane)", "Céramides", "Peptides"],
    format: "serum",
    note: "Alternative végane à la mucine d'escargot, avec un profil ingrédients plus complet (céramides, peptides).",
  },
  {
    id: "typology_serum_l36",
    name: "Typology Sérum Unifiant L36",
    brand: "Typology",
    price: 17.9,
    priceConfirmed: false,
    volume: "10 ml",
    skinTypes: ["toutes"],
    concerns: ["rougeurs", "taches"],
    pores: ["toutes"],
    categories: ["traitement"],
    styles: ["classique", "toutes"],
    ageRange: [15, 60],
    lifestyle: [],
    keyIngredients: ["Niacinamide (12%)"],
    format: "serum",
    note: "Cible les rougeurs liées aux imperfections (marques post-acné) — la marque déconseille ce sérum pour les rougeurs d'hypersensibilité/rosacée.",
  },
  {
    id: "aromazone_niacinamide",
    name: "Aroma-Zone Sérum Concentré Niacinamide 10%, Cuivre & Zinc",
    brand: "Aroma-Zone",
    price: 11.9,
    priceConfirmed: true,
    volume: "30 ml",
    skinTypes: ["grasse", "mixte"],
    concerns: ["points_noirs", "rougeurs", "taches", "exces_sebum"],
    pores: ["dilates"],
    categories: ["traitement"],
    styles: ["classique", "toutes"],
    ageRange: [15, 55],
    lifestyle: ["sans_parfum"],
    keyIngredients: ["Niacinamide (10%)", "Zinc PCA", "Cuivre PCA", "Acide hyaluronique"],
    format: "serum",
    note: "Formule naturelle française, resserre les pores et régule le sébum. Bon rapport qualité-prix pour du 10% niacinamide.",
  },
  {
    id: "the_ordinary_niacinamide",
    name: "The Ordinary Niacinamide 10% + Zinc 1%",
    brand: "The Ordinary",
    price: 6.0,
    priceConfirmed: true,
    volume: "30 ml",
    skinTypes: ["grasse", "mixte"],
    concerns: ["points_noirs", "exces_sebum"],
    pores: ["dilates"],
    categories: ["traitement"],
    styles: ["classique", "toutes"],
    ageRange: [15, 55],
    lifestyle: [],
    keyIngredients: ["Niacinamide (10%)", "Zinc PCA"],
    format: "serum",
    note: "Référence du marché pour son rapport prix/efficacité — bon produit d'entrée de gamme pour un MVP.",
  },
  {
    id: "bioderma_sensibio_ar",
    name: "Bioderma Sensibio AR+ Bi-Sérum",
    brand: "Bioderma",
    price: 24.7,
    priceConfirmed: true,
    volume: "30 ml",
    skinTypes: ["toutes"],
    concerns: ["rougeurs", "rides"],
    pores: ["toutes"],
    categories: ["traitement"],
    styles: ["classique", "toutes"],
    ageRange: [25, 65],
    lifestyle: ["sans_parfum"],
    keyIngredients: ["Bakuchiol", "Complexe anti-rougeurs Rosactiv"],
    format: "serum",
    note: "Double action anti-rougeurs et anti-âge, pensé pour les peaux sensibles à tendance couperosique.",
  },
  {
    id: "eucerin_hyaluron_filler",
    name: "Eucerin Hyaluron-Filler Sérum",
    brand: "Eucerin",
    price: 25.0,
    priceConfirmed: false,
    volume: "30 ml",
    skinTypes: ["toutes"],
    concerns: ["rides"],
    pores: ["toutes"],
    categories: ["hydratation"],
    styles: ["age_perfect"],
    ageRange: [35, 75],
    lifestyle: [],
    keyIngredients: ["Acide hyaluronique pur"],
    format: "serum",
    note: "Gamme anti-âge très établie en pharmacie ; prix à reconfirmer selon le format exact (sérum vs. booster vs. crème).",
  },
  {
    id: "centellian24_madeca_cream",
    name: "Centellian24 Madeca Cream",
    brand: "Centellian24",
    price: 22.0,
    priceConfirmed: false,
    volume: "50 ml",
    skinTypes: ["seche", "mixte", "toutes"],
    concerns: ["rougeurs"],
    pores: ["toutes"],
    categories: ["hydratation"],
    styles: ["coreenne"],
    ageRange: [15, 60],
    lifestyle: [],
    keyIngredients: ["Centella Asiatica", "Madecassoside", "Panthénol"],
    format: "creme",
    note: "Crème apaisante barrière, référence coréenne du soin à la centella asiatica pour peaux sensibles/réactives.",
  },
  {
    id: "beautyofjoseon_glow_serum",
    name: "Beauty of Joseon Glow Serum Propolis + Niacinamide",
    brand: "Beauty of Joseon",
    price: 17.0,
    priceConfirmed: true,
    volume: "30 ml",
    skinTypes: ["toutes"],
    concerns: ["points_noirs", "exces_sebum", "rougeurs", "taches"],
    pores: ["dilates", "toutes"],
    categories: ["traitement"],
    styles: ["coreenne"],
    ageRange: [15, 55],
    lifestyle: [],
    keyIngredients: ["Propolis (60%)", "Niacinamide (2%)"],
    format: "serum",
    note: "Best-seller K-beauty, texture miel, régule le sébum et resserre les pores tout en apaisant.",
  },
  {
    id: "erborian_ginseng_power",
    name: "Erborian Ginseng Power Crème",
    brand: "Erborian",
    price: 35.0,
    priceConfirmed: true,
    volume: "50 ml",
    skinTypes: ["toutes"],
    concerns: ["rides"],
    pores: ["toutes"],
    categories: ["hydratation"],
    styles: ["coreenne", "age_perfect"],
    ageRange: [30, 75],
    lifestyle: [],
    keyIngredients: ["Ginseng"],
    format: "creme",
    note: "Marque hybride franco-coréenne, positionnement anti-âge premium — bon pont entre les styles coréen et age perfect.",
  },
  {
    id: "acm_rosakalm",
    name: "ACM Rosakalm Crème Anti-Rougeurs",
    brand: "Labo ACM",
    price: 16.0,
    priceConfirmed: false,
    volume: "40 ml",
    skinTypes: ["toutes"],
    concerns: ["rougeurs"],
    pores: ["toutes"],
    categories: ["hydratation"],
    styles: ["classique", "toutes"],
    ageRange: [18, 70],
    lifestyle: [],
    keyIngredients: [],
    format: "creme",
    note: "Marque dermo-cosmétique française spécialisée rougeurs/couperose. Prix à reconfirmer directement chez le distributeur.",
  },
];

/**
 * Note sur AIME : la marque est surtout positionnée sur les compléments
 * alimentaires beauté (ex. "French Glow" pour la sensibilité/rougeurs) plutôt
 * que sur des soins topiques avec fiches ingrédients/prix vérifiables. Si tu
 * veux l'inclure, il faudra soit republier un vrai soin visage de leur
 * catalogue (baume nettoyant, sérum antioxydant, crème barrière, SPF) après
 * vérification directe sur aime.co, soit envisager une catégorie "compléments"
 * séparée du schéma produit actuel (qui suppose un soin topique).
 */

/**
 * Ce qu'il reste à compléter pour une couverture correcte des 3 styles :
 * - Un nettoyant "coréen" (ex. huile démaquillante de type Heimish/Beauty of
 *   Joseon) pour le double-cleanse — je n'ai pas encore vérifié de fiche
 *   ingrédients fiable pour un produit précis, à rechercher avant intégration.
 * - Un traitement "classique" ciblant spécifiquement les rougeurs (au-delà
 *   du nettoyant Avène) si tu veux équilibrer les catégories par style.
 */
